version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "metal-prices-notification"
s3_bucket = "yatsubashi-cloudformation-artifacts"
s3_prefix = "metal-prices-notification"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
