AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS SAM Template for Metal Prices Notification

Resources:
  PublishMetalPricesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "PublishMetalPricesFunction"
      Description: "貴金属の価格情報を発行する。"
      Timeout: 10
      MemorySize: 128
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      #   Events:
      #     PublishingSchedule:
      #       Type: Schedule
      #       Properties:
      #         Schedule: "cron(0 22 ? * SAN-THU *)" # JST 月-金 7:00
      Role: !GetAtt PublishMetalPricesFunctionRole.Arn
  PublishMetalPricesFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "PublishMetalPricesFunctionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSLambdaExecute"
      Policies:
        - PolicyName: PublishMetalPricesPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "secretsmanager:GetSecretValue"
                Resource: "arn:aws:secretsmanager:ap-northeast-1:949921099367:secret:metals-api-ZMeuUj"
  PublishMetalPricesFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${PublishMetalPricesFunction}
      RetentionInDays: 30
